import ProductDetails from '@/app/Components/ProductDetails'
import React from 'react'
import MyAccount from '../Components/MyAccount';

export const metadata = {
    title: "My Account - Online Store",
    description: "Generated by create next app",
};

export default function page() {
  return (
    <>
        <MyAccount/>
    </>
  )
}
