import ProductDetails from '@/app/Components/ProductDetails'
import React from 'react'

export const metadata = {
    title: "Product Details - Online Store",
    description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <ProductDetails/>
    </>
  )
}
