'use client';

import Footer from "./Components/Footer";
import Header from "./Components/Header";
import "../../public/css/tailwind-ecommerce.css"
import { ToastContainer } from "react-toastify";
import { Provider } from "react-redux";
import { store } from "./Redux Toolkit/ReduxStore";

// export const metadata = {
//   title: "MayBell - Online Store",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <Provider store={ store }>
          <ToastContainer/>
          <Header />
            {children}
          <Footer />
        </Provider>
        
      </body>
    </html>
  );
}